### ISSUE TITLE
[Bug] [update_package] There was an error processing your request.

### ISSUE THREAD

**Issue by EliaHKM** [hwittenborn/mpm#18]
hi,
I'm trying to install alacritty but as the title said I can't use mpm
could you help me
OS: Devuan 3.1
here is pastebin with mpm update --verbose
[https://pastebin.com/NNjgiHBp](url)
thanks

**Comment by hwittenborn** [comment]
I'm on the same version of mpm, and I'm not able to get the issue to reproduce on my end.

I'm thinking it might be your OS version - what happens if you run this command in your terminal?

```sh
echo '{"version":5,"type":"multiinfo","resultcount":1,"results":[{"ID":82,"Name":"mpm","PackageBaseID":29,"PackageBase":"mpm","Version":"3.6.2-1","Description":"Fully-featured reference MPR helper","URL":"https:\/\/github.com\/hwittenborn\/mpm","NumVotes":0,"Popularity":0,"OutOfDate":null,"Maintainer":"hwittenborn","FirstSubmitted":1625183217,"LastModified":1625639167,"URLPath":"\/cgit\/aur.git\/snapshot\/mpm.tar.gz","Depends":["jq","curl"],"Keywords":["makedeb","mpr-helper"]}]}' | jq
```

**Comment by EliaHKM** [comment]
here is the pastebin
[https://pastebin.com/xAP6LfGG](url)

**Comment by hwittenborn** [comment]
I'm not really sure what the issue is then. The error you got (`[update_package] There was an error processing your request.`) should only appear if/when the above command fails, and it doesn't appear to be doing so.

I'm not getting similar results on my end either, everything's just working fine for me.

I'll have to try to look into it, but I'm honestly not quite sure what the issue could be.

**Comment by hwittenborn** [comment]
@EliaHKM If you're still having issue, you might have some luck with [tap](https://github.com/hwittenborn/tap).

All my development's moving over there, with this repository being put into archived mode.

If you still have issues even with tap, feel free to open an issue there.
