### ISSUE TITLE
(Report) nordic-theme-git install failed

### ISSUE THREAD

**Issue by ghost** [hwittenborn/mpm#4]
OS - Pop OS based on Ubuntu 20.10
mpm-alpha was used
Error- `dpkg-deb: error: parsing file '/tmp/a/makedeb/nordic-theme-git/pkg//nordic-theme-git/DEBIAN/control' near line 4 package 'nordic-theme-git':
 'Version' field value 'r124.7e4f95d-1': version number does not start with digit
`

**Comment by hwittenborn** [comment]
I've confirmed the issue on my end - I'm going to need to change some stuff in makedeb, but it might be a couple days while I finish some things with mpm.

**Comment by hwittenborn** [comment]
Due to the direction that the makedeb project is going, this issue is going to be unsupported.

This is an issue with the naming scheme for versions in Debian and Arch. As can be seen in the error logs, Debian doesn't allow package names to start with letters. Arch on the other hand has no such requirement.

If you'd like to look into packaging this yourself though, I'm moving the features for mpm over to the [DUR](https://dur.hunterwittenborn.com/). Feel free to make a package there, or join one of the support rooms if you'd like to make a package request.
