### ISSUE TITLE
(Report) unexicon-sound-theme-git install failed

### ISSUE THREAD

**Issue by ghost** [hwittenborn/mpm#6]
OS - Pop OS based on Ubuntu 20.10
mpm-alpha was used
Error `Couldn't find the following packages: pkgconfig flite-voices`

**Comment by hwittenborn** [comment]
Could you see if it works now? I added info for the package in the commit linked above.

**Comment by hwittenborn** [comment]
Forgot to deal with `flite-voices`.

**Comment by hwittenborn** [comment]
It appears that the `flite-voices` package isn't in the Arch repositories, but is rather an AUR package. You'll need to first build that package, then build this one.

I'll try to add support for AUR dependencies, but I've got to finish some other stuff first.

**Comment by ghost** [comment]
> It appears that the `flite-voices` package isn't in the Arch repositories, but is rather an AUR package. You'll need to first build that package, then build this one.
> 
Today I tried again with `mpm install flite-voices`  which was successful
 but when I ran `mpm install unexicon-sound-theme-git` 
It failed with error

` ==> Starting build()...`
`/tmp/a/makedeb/unexicon-sound-theme-git/PKGBUILD: line 30: ./configure: No such file or directory`
`==> ERROR: A failure occurred in build().`
`    Aborting...`

**Comment by hwittenborn** [comment]
> `./configure: No such file or directory`

It's saying it's trying to run a file named `configure`, but it isn't there (it appears to be needing to run a file named `configure.sh` rather than `configure` when looking at the [repository it pulls from](https://github.com/bbidulock/unexicon-sound-theme).

This is an issue on the maintainer's side, and <s>I'd recommend you file a bug report on its [AUR page](https://aur.archlinux.org/packages/unexicon-sound-theme-git/)</s> I've gone ahead and filed a bug report.
